### ISSUE TITLE
go back last direcotry with custom keybinding, e.g. ``

### ISSUE THREAD

**Issue by GladioFeng** [dedukun/bookmarks.yazi#39]
can i setting the go back last directory with `` like in vim, current, it work with ''

**Comment by dedukun** [comment]
I've created PR #42 which adds a `key` config option to `last_directory`, like the following:

```lua
 	last_directory = { enable = false, persist = false, key= "'" },
```

this way you can change the trigger key for the jump to last directory to whatever you want.

Alternatively, I've also added a `jump_last` arg which directly jumps to the last directory, this way if you still want to maintain the `'` to trigger the other jumps and just have `` to trigger the jump to last directory, you only need to add something like the following to you `keymap.toml`

```lua
[[manager.prepend_keymap]]
on = [ "`", "`" ]
run = "plugin bookmarks jump_last"
desc = "Jump to last"
```

**Comment by GladioFeng** [comment]
it still not work for me after I change the config in keymap and init.lua

**Comment by dedukun** [comment]
Did you checkout to the branch in the PR? I haven't merge it into main.
Also, what's your Yazi version? Can you add the output of `yazi --debug` here?

You don't need to change both the keymap and init.lua, you can just add the keymap for ``

**Comment by GladioFeng** [comment]
I have checkouted to custom_keybinding branch.

![Image](https://github.com/user-attachments/assets/c3bbda17-9a6b-4540-bfcd-b888dc42ab2a)

and blow are my Yazi --dubug output

```txt
Yazi
    Version: 25.2.11 (Homebrew 2025-02-11)
    Debug  : false
    Triple : x86_64-unknown-linux-gnu (linux-x86_64)
    Rustc  : 1.84.1 (e71f9a9a 2025-01-27)

Ya
    Version: 25.2.11 (Homebrew 2025-02-11)

Emulator
    TERM                : Some("xterm-256color")
    TERM_PROGRAM        : None
    TERM_PROGRAM_VERSION: None
    Brand.from_env      : None
    Emulator.detect     : Emulator { kind: Left(Kitty), light: true, cell_size: Some((14, 35)) }

Adapter
    Adapter.matches: Kgp

Desktop
    XDG_SESSION_TYPE           : Some("tty")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: true

WSL
    WSL: false

Neovim
    NVIM          : false
    Neovim version: 0.10.4

Variables
    SHELL           : Some("/usr/bin/zsh")
    EDITOR          : Some("svim")
    VISUAL          : None
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: Some("--tiebreak=begin -x --cycle --wrap --wrap-sign ⇨\"↳ \" -i --prompt=\"\u{f02c7}  \" --marker=\"✓\" --color=\"prompt:123,hl:148,hl+:154,pointer:red,marker:010,bg+:024,gutter:024\" --ansi --height 100% --layout=reverse --bind \"ctrl-/:toggle-wrap,tab:accept,ctrl-y:execute-silent(echo -E -n {2..} | osc-copy -n)+abort,?:toggle-preview\" -1 -0")

Text Opener
    default     : Some(Opener { run: "~/code/projects/General/svim \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "~/code/projects/General/svim \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "~/code/projects/General/svim \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.4
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file          : 5.45
    ueberzugpp    : No such file or directory (os error 2)
    ffmpeg/ffprobe: No such file or directory (os error 2) / No such file or directory (os error 2)
    pdftoppm      : 25.02.0
    magick        : 7.1.1-41
    fzf           : 0.60.0
    fd/fdfind     : 10.2.0 / No such file or directory (os error 2)
    rg            : 14.1.1
    chafa         : 1.14.5
    zoxide        : No such file or directory (os error 2)
    7zz/7z        : No such file or directory (os error 2) / No such file or directory (os error 2)
    jq            : 1.7

Clipboard
    wl-copy/paste: No such file or directory (os error 2) / No such file or directory (os error 2)
    xclip        : No such file or directory (os error 2)
    xsel         : No such file or directory (os error 2)
```

**Comment by dedukun** [comment]
mmh, I don't really see why it wouldn't work for you, can you provide your `init.lua` and `keymap.toml`?
If you don't want to put the full files here you can just add the lines from this plugin, i.e. the `require("bookmarks")...` from the `init.lua` and the keymaps. 
I just want to have a look at your config

**Comment by pedropombeiro** [comment]
Came here looking for the same thing, and "``" is also not working for me. "''" does work.

```toml
[[manager.prepend_keymap]]
on = [ "`", "`" ]
run = "plugin bookmarks jump_last"
desc = "Jump to last"
```

**Comment by GladioFeng** [comment]
init.lua
```lua
-- plugin bookmarks
require("bookmarks"):setup({
	last_directory = { enable = true, persist = false, key = "`" },
	persist = "all",
	desc_format = "parent",
	file_pick_mode = "hover",
	custom_desc_input = true,
	notify = {
		enable = true,
		timeout = 1,
		message = {
			new = "New bookmark '<key>' -> '<folder>'",
			delete = "Deleted bookmark in '<key>'",
			delete_all = "Deleted all bookmarks",
		},
	},
})
```

keymap.toml
```toml
# plugin bookmark ----------------------------------------------------------
[[manager.prepend_keymap]]
on = ["m"]
run = "plugin bookmarks 'save'"
desc = "Save current position as a bookmark"

[[manager.prepend_keymap]]
on = ["`"]
run = "plugin bookmarks 'jump'"
desc = "Jump to a bookmark"

[[manager.prepend_keymap]]
on = ["b", "d"]
run = "plugin bookmarks 'delete'"
desc = "Delete a bookmark"

[[manager.prepend_keymap]]
on = ["b", "D"]
run = "plugin bookmarks 'delete_all'"
desc = "Delete all bookmarks"

# NOTE: not work 
[[manager.prepend_keymap]]
on = [ "`", "`" ]
run = "plugin bookmarks jump_last"
desc = "Jump to last"
```
